const data = [
  // Nike
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    reviews: "(123 reviews)",
    prevPrice: "140.00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    reviews: "(123 reviews)",
    prevPrice: "180.00",
    newPrice: "220",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One",
    reviews: "(98 reviews)",
    prevPrice: "120.00",
    newPrice: "150",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Revolution 6",
    reviews: "(210 reviews)",
    prevPrice: "100.00",
    newPrice: "130",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },

  // Adidas
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Adidas Ultraboost 22",
    reviews: "(320 reviews)",
    prevPrice: "200.00",
    newPrice: "180",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Adidas Runfalcon 3",
    reviews: "(150 reviews)",
    prevPrice: "90.00",
    newPrice: "75",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Adidas Court Bold Heels",
    reviews: "(65 reviews)",
    prevPrice: "120.00",
    newPrice: "95",
    company: "Adidas",
    color: "white",
    category: "heels",
  },

  // Puma
  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Puma RS-X Reinvention",
    reviews: "(140 reviews)",
    prevPrice: "150.00",
    newPrice: "130",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Puma Pacer Future",
    reviews: "(110 reviews)",
    prevPrice: "130.00",
    newPrice: "115",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Puma Smash v2",
    reviews: "(95 reviews)",
    prevPrice: "100.00",
    newPrice: "85",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  // Vans
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Vans Classic Slip-On",
    reviews: "(200 reviews)",
    prevPrice: "80.00",
    newPrice: "70",
    company: "Vans",
    color: "green",
    category: "flat",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Vans Rainbow Chex Skate",
    reviews: "(175 reviews)",
    prevPrice: "90.00",
    newPrice: "185",
    company: "Vans",
    color: "red",
    category: "flat",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Vans Old Skool",
    reviews: "(300 reviews)",
    prevPrice: "110.00",
    newPrice: "95",
    company: "Vans",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61xZlYF6hJL._AC_UY695_.jpg",
    title: "Birkenstock Arizona Soft Footbed",
    reviews: "(210 reviews)",
    prevPrice: "120.00",
    newPrice: "95",
    company: "Birkenstock",
    color: "brown",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71cT0Vv1vDL._AC_UY695_.jpg",
    title: "Teva Original Universal Sandal",
    reviews: "(180 reviews)",
    prevPrice: "70.00",
    newPrice: "60",
    company: "Teva",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61jR1bWQZcL._AC_UY695_.jpg",
    title: "Crocs Classic Sandal",
    reviews: "(300 reviews)",
    prevPrice: "50.00",
    newPrice: "40",
    company: "Crocs",
    color: "white",
    category: "sandals",
  },

  // Heels
  {
    img: "https://m.media-amazon.com/images/I/61oX0WbqZ0L._AC_UY695_.jpg",
    title: "Steve Madden Carrson Heel",
    reviews: "(145 reviews)",
    prevPrice: "100.00",
    newPrice: "85",
    company: "Steve Madden",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71W0z0U8nEL._AC_UY695_.jpg",
    title: "Calvin Klein Gayle Pump",
    reviews: "(190 reviews)",
    prevPrice: "120.00",
    newPrice: "105",
    company: "Calvin Klein",
    color: "red",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61YkZ0Qv3DL._AC_UY695_.jpg",
    title: "Sam Edelman Hazel Pointed Heel",
    reviews: "(160 reviews)",
    prevPrice: "130.00",
    newPrice: "110",
    company: "Sam Edelman",
    color: "white",
    category: "heels",
  },

  // flat
  {
    img: "https://m.media-amazon.com/images/I/61Kk9v0nYUL._AC_UY695_.jpg",
    title: "Clarks Ballet Flat",
    reviews: "(220 reviews)",
    prevPrice: "80.00",
    newPrice: "65",
    company: "Clarks",
    color: "black",
    category: "flat",
  },
  {
    img: "https://m.media-amazon.com/images/I/71fRz8Xq3EL._AC_UY695_.jpg",
    title: "Skechers Cleo Flat",
    reviews: "(140 reviews)",
    prevPrice: "70.00",
    newPrice: "55",
    company: "Skechers",
    color: "blue",
    category: "flat",
  },
  {
    img: "https://m.media-amazon.com/images/I/61b8v7z2tZL._AC_UY695_.jpg",
    title: "Hush Puppies Chaste Ballet Flat",
    reviews: "(175 reviews)",
    prevPrice: "90.00",
    newPrice: "75",
    company: "Hush Puppies",
    color: "green",
    category: "flat",
  },
];

export default data;